### DISCUSSION TITLE
[kyc-match - address] no clear reference about what kind of address should be checked

### DISCUSSION THREAD

**Discussion by GillesInnov35** [camaraproject/KnowYourCustomerMatch#76] [General]
**Problem description**
There isn't any clear reference in the specifications about what kind of address should be checked on operator side
Should we require Home, address, Postal or Installation address ? 
- If not we let the operator define on which of these it'll base the check.
- We also know that it depends mostly on the back end solution called by the API.

**Possible evolution**
indicate clearly in API specifications what kind of address is required according to what information the user should be able to input.

BR
Gilles

**Comment by KevScarr** [comment]
Sharing Info: For contract customer (PAYM) we typically have multiple addresses on the account, billing and shipping can be different.  For casual (PAYG) customers its likely to be one address.
We prioritize billing address over shipping address when we perform our checks today.

**Comment by HuubAppelboom** [comment]
We have two addresses, a contact address which is used for all official communication with the contract owner, and a billing address.  

We typically use the contact address with Match, because that is usually where the contract owner resides, sim cards and handsets are beings shipped to etc.
A separate billing address is often used when you want a paper bill to be send to your bookkeeper. There are not many that have this as a separate address, but it does happen.

**Comment by HuubAppelboom** [comment]
As a suggestion, what may be a good idea is to verify an address against all possible adresses the Operator holds (and return the results of the best matching address).  That way it doesn't really matter what use case it is etc.

**Comment by GillesInnov35** [comment]
At Orange, we use the contact address for the Match service. As proposed by Huub I think we could specify to check all addresses  held by the MNO.
BR
Gilles

**Comment by PaoloCommissari** [comment]
### Hi everyone,

Jumping in from TIM (Italy) to contribute to this interesting discussion.

In Italy — and generally in countries with civil law systems — individuals may legally declare multiple types of addresses with specific meanings and legal implications. For instance, we often manage:

- Residence (place of official legal residence)
- Domicile (designated legal address for service or communication)
- Temporary residence (current place of stay)
- Alongside more common types like contact and billing addresses

These distinctions are relevant not only for legal compliance, but also for identity verification, fraud prevention, and regulatory reporting.

### What do you think of a model like this?
A flexible structure that allows (but doesn't require) address classification, while supporting simpler use cases (like only CONTACT and BILLING) for those who don't need legal granularity.

```
addresses:
  type: array
  items:
    type: object
    required: [streetName, streetNumber, locality, postalCode, country]
    properties:
      addressType:
        type: string
        enum: [RESIDENCE, DOMICILE, TEMPORARY_RESIDENCE, CONTACT, BILLING, SHIPPING, REGISTERED, OTHER]
        description: Optional. Legal or functional classification of the address.
      streetName:
        type: string
      streetNumber:
        type: string
      houseNumberExtension:
        type: string
      locality:
        type: string
      region:
        type: string
      postalCode:
        type: string
      country:
        type: string
        description: ISO 3166-1 alpha-2 code
```

### Example
```
"addresses": [
  {
    "addressType": "RESIDENCE",
    "streetName": "Via Roma",
    "streetNumber": "12",
    "houseNumberExtension": "B",
    "locality": "Torino",
    "region": "Piemonte",
    "postalCode": "10121",
    "country": "IT"
  },
  {
    "addressType": "DOMICILE",
    "streetName": "Corso Buenos Aires",
    "streetNumber": "45",
    "locality": "Milano",
    "region": "Lombardia",
    "postalCode": "20124",
    "country": "IT"
  },
  {
    "addressType": "BILLING",
    "streetName": "Via della Conciliazione",
    "streetNumber": "4",
    "locality": "Roma",
    "region": "Lazio",
    "postalCode": "00193",
    "country": "IT"
  }
]

```
This would allow each operator to decide how much they want to use addressType:
- Some (like [HuubAppelboom](https://github.com/HuubAppelboom) - KPN) could keep it simple and use just one or two addresses.
- Others (like TIM) could leverage the legal granularity when required by regulation or business logic.

We’re happy to refine this together with the community!

Thanks 

**P.**

**Comment by HuubAppelboom** [comment]
@PaoloCommissari For the Netherlands, we also have the houseNumberExtension.  
We are also in the process of discussing the minimum supported address attributes (in the Netherlands, postalcode + streetnumber + houseNumberExtension is sufficient to define an address exactly); it may be better to keep things optional, in stead of everything as required.
Please note that there is also an "address" defined as a complete address string in the current specs.

**Comment by HuubAppelboom** [comment]
PS.  One issue is what do you answer with KYC Match when the API Consumer submits for example a DOMICILE address, but the API Provider only has a CONTACT address ?

**Comment by PaoloCommissari** [comment]
Hi @HuubAppelboom ,  

### On minimal address fields & `houseNumberExtension`

Totally agree. In Italy we also make use of `houseNumberExtension`, especially in urban contexts. The Dutch convention of using just `postalCode + streetNumber + houseNumberExtension` as a minimal identifier makes perfect sense — and reinforces the idea that **the model should be flexible** and accommodate national differences.

That’s why in our updated proposal we removed the `required` block altogether and suggest implementers define their own minimal set, based on local regulatory needs. We also added support for a `fullAddress` field as a fallback or for legacy use cases where structured parsing isn't feasible.

Here’s the revised model we're proposing:

```yaml
addresses:
  type: array
  items:
    type: object
    properties:
      addressType:
        type: string
        description: >
          Optional. Legal or functional classification of the address.
          Suggested values: RESIDENCE, DOMICILE, TEMPORARY_RESIDENCE, CONTACT, BILLING,
          SHIPPING, REGISTERED, OTHER. Not restricted to this list.
      streetName:
        type: string
      streetNumber:
        type: string
      houseNumberExtension:
        type: string
      locality:
        type: string
      region:
        type: string
      postalCode:
        type: string
      country:
        type: string
        description: ISO 3166-1 alpha-2 code
      fullAddress:
        type: string
        description: Optional. Unstructured full address as a fallback or legacy format.
```

This allows both granular implementations and simpler ones to coexist.

### On KYC Match and mismatched address types

In terms of matching logic: we propose keeping things as simple and practical as possible.

The API consumer sends an address (with or without `addressType`), and the provider scans its stored addresses to find a match. If a match is found — even if the address type differs — the provider can respond with:

```json
{
  "match": true,
  "matchedAddressType": "CONTACT"
}
```

Optionally, if the consumer provided a specific `addressType`, the provider may include that as `requestedAddressType`:

```json
{
  "match": true,
  "requestedAddressType": "DOMICILE",
  "matchedAddressType": "CONTACT"
}
```

This gives the consumer full context without requiring complex negotiation or introducing false negatives when the address itself is valid but classified differently.

Let us know what you think

Thanks again,  

**P.**
